<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">
    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <OutputType>Exe</OutputType>
        <Nullable>enable</Nullable>
        <ImplicitUsings>disable</ImplicitUsings>
    </PropertyGroup>

    <PropertyGroup>
        <WasmBuildNative>True</WasmBuildNative>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
        <WasmNativeStrip>false</WasmNativeStrip>
        <EmccCompileOptimizationFlag>-O1</EmccCompileOptimizationFlag>
        <RunAOTCompilation>false</RunAOTCompilation>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <Optimize>true</Optimize>
        <WasmNativeStrip>true</WasmNativeStrip>
        <EmccCompileOptimizationFlag>-O3</EmccCompileOptimizationFlag>
        <EmccLinkOptimizationFlag>-O3</EmccLinkOptimizationFlag>
        <RunAOTCompilation>false</RunAOTCompilation>
    </PropertyGroup>

    <ItemGroup>
        <BlazorLinkerDescriptor Include="LinkerDescriptor.xml" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia.Web.Blazor" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ImeSense.Boilerplates.Avalonia\ImeSense.Boilerplates.Avalonia.csproj" />
        <ProjectReference Include="..\ImeSense.Boilerplates.BlazorWrapper\ImeSense.Boilerplates.BlazorWrapper.csproj" />
    </ItemGroup>
</Project>
